const AUTHENTICATE_ROUTE = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
};

const APP_ROUTE = {
  MAIN_TAB: 'MAIN_TAB',
};

const PROFILE_ROUTE = {
  ROOT: 'PROFILE_ROOT',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};
const SETTING_ROUTE = {
  ROOT: 'SETTING_ROUTE',
  SETTING_SCREEN: 'SETTING_SCREEN',
};
const HOME_ROUTE = {
  ROOT: 'HOME_ROOT',
  HOME_SCREEN: 'HOME_SCREEN',
};
const STATISTICAL_ROUTE = {
  ROOT: 'STATISTICAL_ROUTE',
  STATISTICAL_SCREEN: 'STATISTICAL_SCREEN',
};
const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
  SETTING_ROUTE,
  STATISTICAL_ROUTE,
  PROFILE_ROUTE,
};

export {AUTHENTICATE_ROUTE, APP_ROUTE, TAB_NAVIGATION_ROOT};
