const AUTHENTICATE_ROUTE = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
};

const APP_ROUTE = {
  MAIN_TAB: 'MAIN_TAB',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
};
const PROFILE_ROUTE = {
  ROOT: 'PROFILE_ROOT',
};
const CATEGORY_ROUTE = {
  ROOT: 'CATEGORY_ROOT',
};

const HOME_ROUTE = {
  ROOT: 'HOME_ROOT',
  HOME_SCREEN: 'HOME_SCREEN',
};

const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
  CATEGORY_ROUTE,
  PROFILE_ROUTE,
};

export {AUTHENTICATE_ROUTE, APP_ROUTE, TAB_NAVIGATION_ROOT};
